### ISSUE TITLE
Implement new server

### ISSUE THREAD

**Issue by TheNirmata** [keelworks/LMS#58]
Implement a brand new server to connect to Next.js 

----
Create a new server using Express.js (and node) implement SSR with Next.js. We are phasing out/ deprecate  the use of Django and Python. 

### Acceptance Criteria

SSR -handle the static HTML pages in the backend 
Express -handles robust data 

### Requirement Documents 

Add sketch / API documents -if possible

### Environment 

Provide test accounts if possible.

**Comment by TheNirmata** [comment]
Refer to ticket #33

**Comment by cyan-graphics** [comment]
![image](https://github.com/user-attachments/assets/40d20860-ac31-45a3-bf64-68fad6f328b2)

**Comment by cyan-graphics** [comment]
![image](https://github.com/user-attachments/assets/94e023e4-f77a-4ab5-b7ee-f82cf0a1fd4e)

**Comment by TheNirmata** [comment]
Great job!
